language: ruby

gemfile:
  - Gemfile

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.9.2
      gemfile: Gemfile.1.8.7
    - rvm: 1.9.3
      gemfile: Gemfile.1.8.7
    - rvm: 2.0.0
      gemfile: Gemfile.1.8.7
    - rvm: jruby-18mode
      gemfile: Gemfile
    - rvm: jruby-19mode
      gemfile: Gemfile.1.8.7

notification:
  - email: false
